In [ ]:
#Câu 1
#a
import numpy as np
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
tong = A + B
tich = 2 * A + 3 * B
print("Tổng A + B:", tong)
print("Tich 2A + 3B:", tich)

Tổng A + B: [2 3 1 6]
Tich 2A + 3B: [ 3 11  2 14]


In [ ]:
#b
import numpy as np
tich_vo_huong = np.dot(A, B)
do_dai_A = np.linalg.norm(A)
do_dai_B = np.linalg.norm(B)
cos_goc = tich_vo_huong/(do_dai_A * do_dai_B)
goc_do = np.degrees(np.arccos(cos_goc))
print("Tích vô hướng A * B:", tich_vo_huong)
print("Góc giữa hai vector A và B: ", round(goc_do, 3))

Tích vô hướng A * B: -5
Góc giữa hai vector A và B:  99.594


In [ ]:
#C
import numpy as np
C = np.array([[2, -1, 3],
              [1, 4, -2],
              [0, 2, 5]
              ])
CTC = np.dot(C.T,C)
print('Ma trận C^TxC = ', CTC)

Ma trận C^TxC =  [[ 5  2  4]
 [ 2 21 -1]
 [ 4 -1 38]]


In [ ]:
#Câu 2
import numpy as np
M = np.array([[2, -1, 3, 0],
              [1, 4, -2, 5],
              [0, 2, 6, -3],
              [-1, 0, 1, 4]
              ])
N = np.array([[1, 3, -2, 0],
              [4, -1, 5, 2],
              [0, 2, 3, -1],
              [-3, 1, 0, 4]
              ])
#a
tich_ma_tran = np.dot(M,N)
print("Tích ma Trận MxN: ", tich_ma_tran)

Tích ma Trận MxN:  [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]


In [ ]:
#b
import numpy as np
M = np.array([[2, -1, 3, 0],
              [1, 4, -2, 5],
              [0, 2, 6, -3],
              [-1, 0, 1, 4]
              ])
dinh_thuc_M = np.linalg.det(M)
print('Đỉnh thức M là: ', round(dinh_thuc_M,5))

Đỉnh thức M là:  409.0


In [ ]:
#c
import numpy as np
N = np.array([[1, 3, -2, 0],
              [4, -1, 5, 2],
              [0, 2, 3, -1],
              [-3, 1, 0, 4]
              ])
hang_N = np.linalg.matrix_rank(N)
print('Hạng của ma trận N là: ', hang_N)

Hạng của ma trận N là:  4


In [ ]:
#Câu 3
import numpy as np

# Khai báo ma trận P và vector hệ số tự do
P = np.array([[3, -1, 0, 2],
              [1, 4, -2, 0],
              [0, 1, 5, -1],
              [2, 0, 1, 3]])

b = np.array([6, 8, 3, 7])

# a) Tìm ma trận nghịch đảo của P
try:
    P_nghichdao = np.linalg.inv(P)
    print(P_nghichdao)
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch.")

# b) Giải hệ phương trình P * x = b
if 'P_nghichdao' in locals():
    x = P_nghichdao @ b
    print(x)

# c) Kiểm tra lại nghiệm
if 'x' in locals():
    check = P @ x
    print(check)
    print(b)
    print(np.allclose(check, b))

[[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.2         0.05714286  0.11428571]
 [-0.03571429 -0.05        0.16428571  0.07857143]
 [-0.32142857 -0.05       -0.12142857  0.50714286]]
[2.         1.71428571 0.42857143 0.85714286]
[6. 8. 3. 7.]
[6 8 3 7]
True


In [ ]:
#Câu 4
# Khai báo ma trận Q
Q = np.array([[5, -2, 1],
              [0, 3, -1],
              [2, 0, 4]])

# a) Tìm giá trị riêng
eigenvalues, eigenvectors = np.linalg.eig(Q)
print(eigenvalues)

# b) Vector riêng tương ứng
print(eigenvectors)

# c) Chuẩn hóa vector riêng (độ dài = 1)
normed_vectors = eigenvectors / np.linalg.norm(eigenvectors)
print(normed_vectors)

[6.3553014+0.j         2.8223493+1.07730381j 2.8223493-1.07730381j]
[[ 0.74846013+0.j         -0.37423006+0.34234215j -0.37423006-0.34234215j]
 [-0.18941773+0.j          0.09470887+0.57433055j  0.09470887-0.57433055j]
 [ 0.63555359+0.j          0.63555359+0.j          0.63555359-0.j        ]]
[[ 0.43212366+0.j         -0.21606183+0.19765133j -0.21606183-0.19765133j]
 [-0.10936038+0.j          0.05468019+0.3315899j   0.05468019-0.3315899j ]
 [ 0.36693703+0.j          0.36693703+0.j          0.36693703-0.j        ]]


In [ ]:
#Câu 5
# Ma trận hệ số R và vector hằng số b
R = np.array([[4,-1, 2],
              [1, 3, -2],
              [0, 2, 5]])
b = np.array([12, 5, 9])

# a) Giải hệ phương trình Rx = b
x = np.linalg.solve(R, b)
print(x)

# b) Kiểm tra khả nghịch và nhân ngược lại
try:
    R_inv = np.linalg.inv(R)
    print(R_inv)
    # Kiểm tra lại nghiệm
    check = R @ x
    print(check)
    print(b)
except np.linalg.LinAlgError:
    print("b) R không khả nghịch.")

# c) Chuẩn Frobenius của R
fro_norm = np.linalg.norm(R, ord='fro')
print(round(fro_norm, 3))

[2.78823529 1.52941176 1.18823529]
[[ 0.22352941  0.10588235 -0.04705882]
 [-0.05882353  0.23529412  0.11764706]
 [ 0.02352941 -0.09411765  0.15294118]]
[12.  5.  9.]
[12  5  9]
8.0
