In [5]:
#Bài 1
#Câu a
import numpy as np
u = np.array([2,-1,5,0])
v = np.array([4,3,1,-1])
w = np.array([-6,2,0,3])
x = 2*u-(v+3*w)
print (x)
#Câu b
x = 0.5*(2*u-v-3*w)
print(x)

[ 18 -11   9  -8]
[ 9.  -5.5  4.5 -4. ]


In [6]:
#Bài 2
from numpy import linalg
A = np.matrix([[0,-1,3],[1,1,1],[4,2,2]])
B = np.array([-1,-2,-2])
X = np.linalg.solve(A,B)
print(X)

[ 1. -2. -1.]


In [8]:
#Bài 3
A = np.matrix([[1,0],[0,0]])
B = np.matrix([[0,0],[0,1]])
from numpy import linalg as LA
#Phương pháp 1
LA.inv(A+B)
#Phương pháp 2
LA.det(A)
LA.det(B)
LA.det(A+B)

np.float64(1.0)

In [9]:
#Bài 4
import sympy as sp
x, y = sp.symbols('x y')
A = sp.Matrix([[x, y],[y, x]])
x1, y1 = sp.symbols('x1 y1')
A1 = sp.Matrix([[x1, y1],[y1, x1]])
x2, y2 = sp.symbols('x2 y2')
A2 = sp.Matrix([[x2, y2],[y2, x2]])
A1.T
(A1+A2).T
((A1+A2).T).equals(A1+A2)
c = sp.symbols('c')
print (c*A)
((c*A).T).equals(c*A)

Matrix([[c*x, c*y], [c*y, c*x]])


True

In [10]:
#Bài 7
import sympy as sp
c1, c2 = sp.symbols('c1 c2')
u1, u2 = sp.symbols('u1 u2')
sp.solve([c1+c2-u1,c1-c2-u2])
u1 = 0
u2 = 0
sp.solve([c1+c2-u1,c1-c2-u2])

{c1: 0, c2: 0}

In [12]:
#Bài 2.2
#Câu a
import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,2])
P_caua = (P.T + vecdelta).T
print (P_caua)
#Câu b
import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,-2])
matran_biendoi = np.array([[1.0,0.0],
                           [0.0,2.0]])
P_caub = (P.T @matran_biendoi + vecdelta).T
print(P_caub)

[[4 4 7 7 5 5 6 6 5 5]
 [2 7 7 6 6 5 5 4 4 2]]
[[ 4.  4.  7.  7.  5.  5.  6.  6.  5.  5.]
 [-2.  8.  8.  6.  6.  4.  4.  2.  2. -2.]]


In [13]:
#Câu 3.1
import sympy as sp
from sympy import lambdify
x1, x2, x3 = sp.symbols('x1 x2 x3')
bieuthuc1 = x1 - x2 + x3
f1 = lambdify([x1, x2, x3], bieuthuc1, 'numpy')
a, b, c = sp.symbols('a b c')
d, e, f = sp.symbols('d e f')
f1(a, b, c)
f1(d, e, f)
f1(a+d, b+e, c+f)
f1(a,b,c) + f1(d,e,f) == f1(a+d, b+e, c+f)
(f1(a,b,c) + f1(d,e,f)).equals( f1(a+d, b+e, c+f))
q = sp.symbols('q')
(q*f1(a,b,c) + f1(d,e,f)).equals(f1(q*a+d, q*b+e, q*c+f).expand())
bieuthuc2 = 2*x2 + 3* x3
f2 = lambdify([x1, x2, x3], bieuthuc2, 'numpy')
(q*f2(a,b,c) + f2(d,e,f)).equals(f2(q*a+d, q*b+e, q*c+f).expand())

True

In [14]:
#Bài 3.3
import sympy as sp
a, b = sp.symbols('a b')
x, y = sp.symbols('x y')
sp.solve([a+3*b-x, 2*a+5*b-y],[a,b])
fu1 = np.array([1,1,2])
fu2 = np.array([4,2,1])
fu = a*fu1 + b*fu2
print (fu)
fu = a.subs(a, -5*x + 3*y)*fu1 + b.subs(b, 2*x - y)*fu2
print (fu)

[a + 4*b a + 2*b 2*a + b]
[3*x - y -x + y -8*x + 5*y]


In [15]:
#Bài 3.4
x1, x2, x3 = sp.symbols('x1 x2 x3')
sp.solve([x1+x2-x3, 2*x1+3*x2-x3, 3*x1+5*x2-x3],[x1, x2, x3])

{x1: 2*x3, x2: -x3}

In [16]:
#Bài 3.6
import numpy as np
import math
from scipy import linalg as LA
B = np.matrix([[1.0/math.sqrt(2), 1.0/math.sqrt(2)],
 [-1.0/math.sqrt(2),1.0/math.sqrt(2)]])
LA.orth(B)

array([[-0.70710678,  0.70710678],
       [ 0.70710678,  0.70710678]])