Bài tập tại lớp

In [22]:
# Bài 1
def scale(a, v):
  return[a*vi for vi in v]
v = [3,5,7]
scale(10, v)

[30, 50, 70]

In [23]:
def sumvector(v, w):
  return[vi+wi for (vi,wi) in zip(v, w)]
v = [3,5,7]
w = [2,4,6]
sumvector(v,w)

[5, 9, 13]

In [24]:
def dotvector(v, w):
  return sum([vi*wi for (vi, wi) in zip(v, w)])
dotvector(v, w)

68

In [26]:
def lenvector(v):
  return dotvector(v,v)
lenvector(w)

56

In [31]:
#Bài 2
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
scores >= 0
scores < 0
np.select([scores >=0, scores < 0],['so duong','so am'], default='unknown')


array(['so am', 'so duong', 'so duong', 'so am', 'so duong', 'so am'],
      dtype='<U8')

In [32]:
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
np.select([scores >0, scores ==0, scores < 0],['so duong', 'so 0','so am'], default='unknown')

array(['so am', 'so duong', 'so duong', 'so 0', 'so am', 'so duong',
       'so 0', 'so am'], dtype='<U8')

In [36]:
#Bài 3
import numpy as np
from scipy import linalg, sparse
D = np.matrix([ [3,4], [5,6] ])
print(D)
C = np.matrix(np.random.random((5,7)))
print(C)
A = np.matrix(np.random.random((2,2)))
print(A)
b = np.array([(1+5j, 2j, 3j),(4, 5, 6)])
B = np.asmatrix(b)
print(b)
print(B)

[[3 4]
 [5 6]]
[[0.31980555 0.64569719 0.50033434 0.70397336 0.50839066 0.69326777
  0.72937307]
 [0.04993196 0.27004104 0.07057901 0.64434399 0.32932358 0.29937499
  0.37916082]
 [0.60878696 0.79307017 0.16799156 0.04176452 0.49927777 0.48399382
  0.4177812 ]
 [0.49945362 0.64317773 0.35920083 0.53926176 0.68507032 0.52232797
  0.70728816]
 [0.6540438  0.67383749 0.23042846 0.78275142 0.96648828 0.32697615
  0.87115358]]
[[0.08870242 0.94876772]
 [0.24624663 0.00188306]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [37]:
import numpy as np
b = np.array([(1+5j, 2j, 3j),(4, 5,
6)])
B = np.asmatrix(b)
print(B)
print(b)
A = np.matrix(np.random.random((2,2)))
print(A)
print(A.T)
print(A.I)
linalg.inv(A)
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_lower = np.tril(M)
print(M_lower)
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_upper = np.triu(M)
print(M_upper)
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
v_diag = np.diag(M)
print (v_diag)
M_diag = np.diag(v_diag)
print (M_diag)

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[0.26949704 0.83048136]
 [0.92665004 0.67665435]]
[[0.26949704 0.92665004]
 [0.83048136 0.67665435]]
[[-1.15232238  1.41428523]
 [ 1.57805767 -0.45894551]]
[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]
[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]
[-1 -2 -2]
[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


In [ ]:
#Bài 4
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
sp.solve([x*x+2-6, y-1-6,x+z-1, 2*x*x-8, z*z+4-5,y-z-8], [x, y, z])

In [ ]:
x = [1,2,3]
y = [1,2,3]
print(all(x[]))