In [1]:
#Bài 1.1
import numpy as np
D = np.array([[1,2],[3,4]])
E = np.empty_like(D)
np.copyto(E,D)
E = np.array([[1,2],[3,5]])
np.copyto(E,D)
print(E)

[[1 2]
 [3 4]]


In [5]:
#Bài 1.2
x = np.array([['a,b'],['c,d']])
y = 'x'

#C = np.matrix([[x,y],[1,2]])
#print(C)

#A = np.matrix([[[1,2],[3,4],[5,6],[7,8]]])

A = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(A)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [6]:
#Bài 1.3
from numpy import matlib
G = matlib.identity(5)
print(6)
H = matlib.randn(3,2)
print(H)
K = matlib.zeros([4,4])
print(K)

6
[[ 1.08683728 -0.67009871]
 [ 0.31789832  0.21522443]
 [ 0.74648902 -0.78234243]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
#Bài 2.2
import numpy as np
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]
M = np.matrix([[1,2],[3,4]])
for i in range(len(c)):
  ci = np.matrix([[1,1],[1,0]])
  ci[0, 0] = c[i]
  if (i==0):
    M = ci
  else:
    M = M.dot(ci)
print(M)
print (M[0,0]/M[1,0])

[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936


In [11]:
#Bài 3.2
import numpy as np
X = np.array([[1,1],[1,2],[1,3],[1,4],[1,5]])
Y = np.array([[1],[2],[4],[4],[6]])
XT = X.transpose()
A1 = XT.dot(X)
A2 = XT.dot(Y)
A = A1.dot(A2)
print(A)

[[1030]
 [3720]]


In [14]:
#Bài tập chương 5
import numpy as np
def bpcuctieu(a):
  b = []
  o1 = []
  for i in range(len(a)):
    o1.append(1.0)
    b.append((i+1)*1.0)
  x = np.array([o1,b])
  u = np.dot(x,x.T)
  y = np.array(a)
  from numpy import linalg
  u_1 = np.linalg.inv(u)
  v = np.dot(u_1,x)
  A = np.dot(v,y)
  return A
du_lieu = [10.0, 8,7,5,2]
bpcuctieu(du_lieu)

array([12.1, -1.9])