In [3]:
#Câu 1
#a
import numpy as np
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
tong = A + B
tich = 3 * A - 2 * B
print("Tong A + B:", tong)
print("Tich 3A - 2B:", tich)

Tong A + B: [3 3 1 5]
Tich 3A - 2B: [  4 -11  13 -10]


In [19]:
#b
import numpy as np
tich_vo_huong = np.dot(A, B)
do_dai_A = np.linalg.norm(A)
do_dai_B = np.linalg.norm(B)
cos_goc = tich_vo_huong/(do_dai_A * do_dai_B)
goc_do = np.degrees(np.arccos(cos_goc))
print("Tích vô hướng A * B:", tich_vo_huong)
print('Góc giữa hai vector A và B: ', round(goc_do))

Tich vo huong A * B: -8
Góc giữa hai vector A và B:  108


In [23]:
#C
import numpy as np
C = np.array([[1, 2, -1],
              [0, 3, 4],
              [2, -1, 0]
              ])
CTC = np.dot(C.T,C)
print('Ma trận C^TxC = ', CTC)

Ma trận C^TxC =  [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


In [25]:
#Câu 2
import numpy as np
M = np.array([[1, 2, 3, 0],
              [4, 5, 6, 1],
              [7, 8, 9, 2],
              [0, 1, 1, 0]
              ])
N = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11],
              [12, 13, 14, 15]
              ])
#a
tich_ma_tran = np.dot(M,N)
print("Tích ma Trận MxN: ", tich_ma_tran)

Tích ma Trận MxN:  [[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]


In [38]:
#b
import numpy as np
M = np.array([[1, 2, 3, 0],
              [4, 5, 6, 1],
              [7, 8, 9, 2],
              [0, 1, 1, 0]
              ])
dinh_thuc_M = np.linalg.det(M)
print('Đỉnh thức M là: ', round(dinh_thuc_M,5))

Đỉnh thức M là:  0.0


In [34]:
#c
import numpy as np
N = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11],
              [12, 13, 14, 15]
              ])
hang_N = np.linalg.matrix_rank(N)
print('Hạng của ma trận N là: ', hang_N)

Hạng của ma trận N là:  2


In [ ]:
#Câu 3
import numpy as np

# Khai báo ma trận P và vector hệ số tự do
P = np.array([[2, 1, 0, 1],
              [0, 3, 1, -1],
              [1, 0, 4, 2],
              [0, 1, 0, 3]])

b = np.array([4, 7, 9, 5])

# a) Tìm ma trận nghịch đảo của P
try:
    P_nghichdao = np.linalg.inv(P)
    print(P_nghichdao)
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch.")

# b) Giải hệ phương trình P * x = b
if 'P_nghichdao' in locals():
    x = P_nghichdao @ b
    print(x)

# c) Kiểm tra lại nghiệm
if 'x' in locals():
    check = P @ x
    print(check)
    print(b)
    print(np.allclose(check, b))

In [ ]:
#Câu 4
# Khai báo ma trận Q
Q = np.array([[4, -1, 0],
              [1, 3, -2],
              [0, 1, 2]])

# a) Tìm giá trị riêng
eigenvalues, eigenvectors = np.linalg.eig(Q)
print(eigenvalues)

# b) Vector riêng tương ứng
print(eigenvectors)

# c) Chuẩn hóa vector riêng (độ dài = 1)
normed_vectors = eigenvectors / np.linalg.norm(eigenvectors)
print(normed_vectors)

In [ ]:
#Câu 5
# Ma trận hệ số R và vector hằng số b
R = np.array([[1, -2,  3],
              [2,  0,  1],
              [-1, 1,  4]])
b = np.array([10, 8, 7])

# a) Giải hệ phương trình Rx = b
x = np.linalg.solve(R, b)
print(x)

# b) Kiểm tra khả nghịch và nhân ngược lại
try:
    R_inv = np.linalg.inv(R)
    print(R_inv)
    # Kiểm tra lại nghiệm
    check = R @ x
    print(check)
    print(b)
except np.linalg.LinAlgError:
    print("b) R không khả nghịch.")

# c) Chuẩn Frobenius của R
fro_norm = np.linalg.norm(R, ord='fro')
print(round(fro_norm, 3))